### ISSUE TITLE
pack jap name file failed.

### ISSUE THREAD

**Issue by bynejake** [crskycode/NekoGameSDK_PackTool#1]
[WAFFLE] 人間不信の錬金術師と元兵士のホムンクルス  这游戏有一些日文名字的文件。

测了一下，打包一个test.txt之后，是能够被garbro识别解压或者用crass解包的。
但是改成 -> 魔王魂 効果音 ジッポ-着火音.txt打包之后就无法识别或者解包。

**Comment by crskycode** [comment]
已经修了。
