### ISSUE TITLE
About NekoSdk

### ISSUE THREAD

**Issue by linakima** [crskycode/NekoGameSDK_PackTool#2]
Hi. 
On the [f95 forum](https://f95zone.to/threads/tools-for-waffle-games-pak-files.138856/#post-9841071) I found your nekosdk for working with game texts. 
But it doesn't work with the [English version of the game](https://vndb.org/v2762). 
Can you help me?

![1](https://github.com/crskycode/NekoGameSDK_PackTool/assets/34077156/3be8bcb6-d974-4ef2-9e34-ac6726f69885)
[files.zip](https://github.com/crskycode/NekoGameSDK_PackTool/files/12264529/files.zip)

**Comment by crskycode** [comment]
This repo not the text tool

**Comment by linakima** [comment]
Yes, this thread is about the packing tool. I didn't know where else to post, so I posted here.
So you have nothing to do with this text tool and I was misled?
